version: "3"

services:

  app:
    build: uparser
    env_file:
      - ./uparser/.env
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./uparser/.env

volumes:
  postgres_data:
    driver: local
