# Generated by Django 4.1.7 on 2023-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveBigIntegerField(verbose_name='Line number')),
                ('order_no', models.PositiveBigIntegerField(verbose_name='Order number')),
                ('due_date', models.DateField(verbose_name='Order due date')),
                ('value_usd', models.PositiveBigIntegerField(verbose_name='Order line value in USD')),
                ('value_rub', models.FloatField(blank=True, null=True, verbose_name='Order line value in RUB')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('line_no', 'order_no'), name='order_line_pk'),
        ),
    ]
